// Predefined affirmation templates
// Predefined affirmation templates – extended “Wheel of Life”
export const AFFIRMATION_TEMPLATES = {
  en: [
    /* ---------- 1. Career & Business ---------- */
    {
      id: "career",
      title: "Career & Business",
      affirmations: [
        "I am happy to build a fulfilling career",
        "I am happy to have clear professional goals",
        "I am happy to possess world-class skills",
        "I am happy to lead inspiring teams",
        "I am happy to have mentors who elevate me",
        "I am happy to attract ideal clients and projects",
        "I am happy to create innovative solutions",
        "I am happy to turn challenges into growth",
        "I am happy to communicate with impact",
        "I am happy to negotiate win-win outcomes",
        "I am happy to earn recognition for my work",
        "I am happy to maintain healthy work–life balance",
        "I am happy to learn something new every day",
        "I am happy to stay focused on high-leverage tasks",
        "I am happy to delegate effectively",
        "I am happy to celebrate my achievements",
        "I am happy to collaborate with brilliant minds",
        "I am happy to handle pressure with calm",
        "I am happy to adapt to any market shift",
        "I am happy to inspire others by example",
        "I am happy to enjoy meaningful, lucrative work",
        "I am happy to thrive in a career that serves and enriches the world",
      ],
    },

    /* ---------- 2. Finances & Wealth ---------- */
    {
      id: "finance",
      title: "Finances & Wealth",
      affirmations: [
        "I am happy to have abundant cash flow",
        "I am happy to possess multiple income streams",
        "I am happy to make smart investment choices",
        "I am happy to manage money with ease",
        "I am happy to enjoy financial freedom",
        "I am happy to save and grow my assets",
        "I am happy to attract profitable opportunities",
        "I am happy to spend consciously and joyfully",
        "I am happy to protect my wealth wisely",
        "I am happy to give generously without fear",
        "I am happy to negotiate higher value",
        "I am happy to increase my net worth daily",
        "I am happy to master financial literacy",
        "I am happy to feel secure about my future",
        "I am happy to build lasting legacy wealth",
        "I am happy to earn in alignment with my values",
        "I am happy to feel peace when reviewing finances",
        "I am happy to let money work for me",
        "I am happy to seize timing in the market",
        "I am happy to celebrate every money win",
        "I am happy to experience overflow and abundance",
        "I am happy to live richly while uplifting others",
      ],
    },

    /* ---------- 3. Health & Wellness ---------- */
    {
      id: "health",
      title: "Health & Wellness",
      affirmations: [
        "I am happy to feel vibrant energy every morning",
        "I am happy to nourish my body with whole foods",
        "I am happy to possess a strong immune system",
        "I am happy to move my body joyfully",
        "I am happy to breathe deeply and calmly",
        "I am happy to rest and recover fully",
        "I am happy to maintain an ideal weight",
        "I am happy to practise excellent posture",
        "I am happy to drink plenty of refreshing water",
        "I am happy to enjoy restorative sleep",
        "I am happy to release stress swiftly",
        "I am happy to cultivate mental clarity",
        "I am happy to stretch and stay flexible",
        "I am happy to feel grateful for my healthy heart",
        "I am happy to glow with natural confidence",
        "I am happy to listen to my body’s wisdom",
        "I am happy to schedule regular check-ups",
        "I am happy to balance work, rest and play",
        "I am happy to avoid harmful substances",
        "I am happy to radiate vitality wherever I go",
        "I am happy to heal quickly and completely",
        "I am happy to embody lifelong wellness in mind, body and spirit",
      ],
    },

    /* ---------- 4. Love & Relationships ---------- */
    {
      id: "relationships",
      title: "Love & Relationships",
      affirmations: [
        "I am happy to give and receive unconditional love",
        "I am happy to communicate with openness",
        "I am happy to listen with empathy",
        "I am happy to respect healthy boundaries",
        "I am happy to express affection freely",
        "I am happy to appreciate my partner daily",
        "I am happy to create memorable moments",
        "I am happy to forgive and let go quickly",
        "I am happy to grow together through challenges",
        "I am happy to share honest feelings safely",
        "I am happy to inspire my loved one’s dreams",
        "I am happy to celebrate our differences",
        "I am happy to cultivate deep trust",
        "I am happy to support mutual independence",
        "I am happy to resolve conflicts peacefully",
        "I am happy to prioritise quality time",
        "I am happy to surprise my partner with joy",
        "I am happy to attract people who uplift me",
        "I am happy to keep romance alive",
        "I am happy to be authentic in love",
        "I am happy to grow intimacy and laughter",
        "I am happy to co-create a love that nourishes our souls",
      ],
    },

    /* ---------- 5. Family & Friends ---------- */
    {
      id: "family",
      title: "Family & Friends",
      affirmations: [
        "I am happy to feel connected to my family",
        "I am happy to honour our shared roots",
        "I am happy to express gratitude for my parents",
        "I am happy to bond with my siblings in joy",
        "I am happy to create new family traditions",
        "I am happy to show up when loved ones need me",
        "I am happy to celebrate milestones together",
        "I am happy to offer unconditional support",
        "I am happy to share laughter and stories",
        "I am happy to respect each person’s uniqueness",
        "I am happy to keep old friendships alive",
        "I am happy to welcome new friends warmly",
        "I am happy to plan meaningful gatherings",
        "I am happy to communicate with kindness",
        "I am happy to resolve misunderstandings swiftly",
        "I am happy to forgive family members fully",
        "I am happy to accept love from my circle",
        "I am happy to practise patience and compassion",
        "I am happy to uplift family dreams",
        "I am happy to be a source of positivity",
        "I am happy to feel safe, loved, and supported",
        "I am happy to nurture bonds that last a lifetime",
      ],
    },

    /* ---------- 6. Personal Growth ---------- */
    {
      id: "growth",
      title: "Personal Growth & Learning",
      affirmations: [
        "I am happy to expand my mind every day",
        "I am happy to seek wisdom from every source",
        "I am happy to learn from my mistakes",
        "I am happy to read books that inspire me",
        "I am happy to invest in my education",
        "I am happy to practise new languages",
        "I am happy to refine my talents",
        "I am happy to challenge limiting beliefs",
        "I am happy to stay curious and open-minded",
        "I am happy to welcome constructive feedback",
        "I am happy to set clear learning goals",
        "I am happy to track my personal growth",
        "I am happy to embrace lifelong learning",
        "I am happy to meditate and reflect often",
        "I am happy to develop emotional intelligence",
        "I am happy to stay disciplined and consistent",
        "I am happy to celebrate progress, not perfection",
        "I am happy to mentor and be mentored",
        "I am happy to turn knowledge into action",
        "I am happy to align growth with my purpose",
        "I am happy to unfold my highest potential",
        "I am happy to evolve into the best version of myself",
      ],
    },

    /* ---------- 7. Fun & Recreation ---------- */
    {
      id: "fun",
      title: "Fun & Recreation",
      affirmations: [
        "I am happy to make time for play",
        "I am happy to explore new hobbies",
        "I am happy to laugh loudly and often",
        "I am happy to travel and discover",
        "I am happy to dance like no one is watching",
        "I am happy to sing with joy",
        "I am happy to enjoy nature’s beauty",
        "I am happy to be spontaneous",
        "I am happy to celebrate small wins",
        "I am happy to attend uplifting events",
        "I am happy to try creative arts",
        "I am happy to relax without guilt",
        "I am happy to schedule mini-adventures",
        "I am happy to bring fun into routine tasks",
        "I am happy to play sports for pleasure",
        "I am happy to savour delicious food",
        "I am happy to capture joyful memories",
        "I am happy to share laughter with friends",
        "I am happy to feel youthful at any age",
        "I am happy to balance work with play",
        "I am happy to add excitement to life",
        "I am happy to live each day with light-hearted wonder",
      ],
    },

    /* ---------- 8. Environment & Living Space ---------- */
    {
      id: "environment",
      title: "Environment & Living Space",
      affirmations: [
        "I am happy to live in a clean, inspiring space",
        "I am happy to organise my surroundings with ease",
        "I am happy to keep only items that bring joy",
        "I am happy to refresh my home with natural light",
        "I am happy to breathe fresh, healthy air",
        "I am happy to decorate with beauty and intention",
        "I am happy to maintain a clutter-free desk",
        "I am happy to feel safe and comfortable at home",
        "I am happy to welcome guests warmly",
        "I am happy to nurture plants that thrive",
        "I am happy to recycle and reduce waste",
        "I am happy to support eco-friendly habits",
        "I am happy to respect public spaces",
        "I am happy to design spaces that spark creativity",
        "I am happy to keep my car clean and functional",
        "I am happy to enjoy inspiring views",
        "I am happy to repair and maintain promptly",
        "I am happy to add uplifting scents and sounds",
        "I am happy to create cozy rest areas",
        "I am happy to honour sacred quiet zones",
        "I am happy to feel grounded wherever I am",
        "I am happy to inhabit environments that nurture my best self",
      ],
    },

    /* ---------- 9. Spirituality & Inner Peace ---------- */
    {
      id: "spirituality",
      title: "Spirituality & Inner Peace",
      affirmations: [
        "I am happy to feel connected to a higher purpose",
        "I am happy to meditate with ease",
        "I am happy to trust my inner guidance",
        "I am happy to practise gratitude daily",
        "I am happy to cultivate compassion for all beings",
        "I am happy to forgive myself completely",
        "I am happy to surrender worries to the universe",
        "I am happy to embrace silence and stillness",
        "I am happy to see divinity in everyday life",
        "I am happy to align actions with my values",
        "I am happy to live in the present moment",
        "I am happy to spread loving-kindness",
        "I am happy to journal my spiritual insights",
        "I am happy to chant or pray mindfully",
        "I am happy to respect all paths to truth",
        "I am happy to breathe peace into each cell",
        "I am happy to release judgment and blame",
        "I am happy to celebrate sacred rituals",
        "I am happy to feel guided and protected",
        "I am happy to shine my inner light outward",
        "I am happy to experience oneness with life",
        "I am happy to radiate serenity, faith, and love",
      ],
    },

    /* ---------- 10. Contribution & Community ---------- */
    {
      id: "contribution",
      title: "Contribution & Community",
      affirmations: [
        "I am happy to share my gifts generously",
        "I am happy to volunteer my time and skills",
        "I am happy to uplift my community",
        "I am happy to mentor those who seek guidance",
        "I am happy to donate resources joyfully",
        "I am happy to support social causes",
        "I am happy to speak up for justice",
        "I am happy to empower others to succeed",
        "I am happy to practise random acts of kindness",
        "I am happy to collaborate on positive change",
        "I am happy to inspire hope through action",
        "I am happy to celebrate collective wins",
        "I am happy to listen to community needs",
        "I am happy to protect the vulnerable",
        "I am happy to lead with integrity",
        "I am happy to teach what I have learned",
        "I am happy to create opportunities for others",
        "I am happy to plant seeds for future generations",
        "I am happy to amplify diverse voices",
        "I am happy to build inclusive spaces",
        "I am happy to serve with a joyful heart",
        "I am happy to leave the world better than I found it",
      ],
    },
  ],

  /* ---------------------------------------------------------------- */
  /* ---------------------------- TIẾNG VIỆT ------------------------- */
  /* ---------------------------------------------------------------- */
  vi: [
    /* ---------- 1. Sự Nghiệp & Kinh Doanh ---------- */
    {
      id: "career",
      title: "Sự Nghiệp & Kinh Doanh",
      affirmations: [
        "Tôi hạnh phúc là người dẫn đầu trong sự nghiệp của mình",
        "Tôi hạnh phúc có mục tiêu nghề nghiệp rõ ràng",
        "Tôi hạnh phúc sở hữu kỹ năng xuất sắc để vượt mọi thử thách",
        "Tôi hạnh phúc là người lãnh đạo truyền cảm hứng",
        "Tôi hạnh phúc có những người cố vấn tuyệt vời",
        "Tôi hạnh phúc thu hút dự án và khách hàng lý tưởng",
        "Tôi hạnh phúc sáng tạo giải pháp đột phá",
        "Tôi hạnh phúc biến thử thách thành cơ hội phát triển",
        "Tôi hạnh phúc giao tiếp mạnh mẽ và thuyết phục",
        "Tôi hạnh phúc thương lượng những thỏa thuận đôi bên cùng thắng",
        "Tôi hạnh phúc được công nhận vì giá trị tôi tạo ra",
        "Tôi hạnh phúc giữ cân bằng giữa công việc và cuộc sống",
        "Tôi hạnh phúc học điều mới mỗi ngày",
        "Tôi hạnh phúc tập trung vào nhiệm vụ có đòn bẩy cao",
        "Tôi hạnh phúc ủy thác công việc hiệu quả",
        "Tôi hạnh phúc ăn mừng thành tựu của mình",
        "Tôi hạnh phúc hợp tác với những bộ óc xuất sắc",
        "Tôi hạnh phúc bình tĩnh dưới áp lực",
        "Tôi hạnh phúc thích nghi với mọi biến động thị trường",
        "Tôi hạnh phúc truyền cảm hứng bằng chính tấm gương của mình",
        "Tôi hạnh phúc tận hưởng công việc ý nghĩa và sinh lợi",
        "Tôi hạnh phúc là người thành công, thịnh vượng và trọn vẹn trong sự nghiệp",
      ],
    },

    /* ---------- 2. Tài Chính & Sự Giàu Có ---------- */
    {
      id: "finance",
      title: "Tài Chính & Sự Giàu Có",
      affirmations: [
        "Tôi hạnh phúc có dòng tiền dồi dào",
        "Tôi hạnh phúc sở hữu nhiều nguồn thu nhập",
        "Tôi hạnh phúc đưa ra quyết định đầu tư thông minh",
        "Tôi hạnh phúc quản lý tiền bạc dễ dàng",
        "Tôi hạnh phúc tận hưởng tự do tài chính",
        "Tôi hạnh phúc tiết kiệm và gia tăng tài sản",
        "Tôi hạnh phúc thu hút cơ hội lợi nhuận cao",
        "Tôi hạnh phúc chi tiêu có ý thức và niềm vui",
        "Tôi hạnh phúc bảo vệ tài sản khôn ngoan",
        "Tôi hạnh phúc cho đi hào phóng không sợ hãi",
        "Tôi hạnh phúc đàm phán giá trị cao hơn",
        "Tôi hạnh phúc gia tăng giá trị ròng mỗi ngày",
        "Tôi hạnh phúc thành thạo kiến thức tài chính",
        "Tôi hạnh phúc an tâm về tương lai tiền bạc",
        "Tôi hạnh phúc xây dựng gia sản bền vững",
        "Tôi hạnh phúc kiếm tiền phù hợp với giá trị sống",
        "Tôi hạnh phúc bình yên khi xem sao kê",
        "Tôi hạnh phúc để tiền làm việc cho mình",
        "Tôi hạnh phúc nắm bắt thời điểm thị trường",
        "Tôi hạnh phúc ăn mừng mọi chiến thắng tài chính",
        "Tôi hạnh phúc sung túc, dư dả và tràn đầy",
        "Tôi hạnh phúc sống giàu có và nâng đỡ cộng đồng",
      ],
    },

    /* ---------- 3. Sức Khỏe & Thể Chất ---------- */
    {
      id: "health",
      title: "Sức Khỏe & Thể Chất",
      affirmations: [
        "Tôi hạnh phúc tràn đầy năng lượng mỗi sáng",
        "Tôi hạnh phúc nuôi dưỡng cơ thể bằng thực phẩm lành mạnh",
        "Tôi hạnh phúc sở hữu hệ miễn dịch mạnh mẽ",
        "Tôi hạnh phúc vận động cơ thể với niềm vui",
        "Tôi hạnh phúc hít thở sâu và bình ổn",
        "Tôi hạnh phúc nghỉ ngơi hồi phục hoàn toàn",
        "Tôi hạnh phúc duy trì cân nặng lý tưởng",
        "Tôi hạnh phúc giữ tư thế chuẩn mực",
        "Tôi hạnh phúc uống đủ nước tinh khiết",
        "Tôi hạnh phúc ngủ sâu và êm dịu",
        "Tôi hạnh phúc giải tỏa căng thẳng nhanh chóng",
        "Tôi hạnh phúc nuôi dưỡng tâm trí minh mẫn",
        "Tôi hạnh phúc căng giãn giúp cơ linh hoạt",
        "Tôi hạnh phúc biết ơn trái tim khỏe mạnh",
        "Tôi hạnh phúc tỏa ra sự tự tin tự nhiên",
        "Tôi hạnh phúc lắng nghe trí tuệ cơ thể",
        "Tôi hạnh phúc kiểm tra sức khỏe định kỳ",
        "Tôi hạnh phúc cân bằng công việc, nghỉ ngơi và vui chơi",
        "Tôi hạnh phúc tránh xa chất gây hại",
        "Tôi hạnh phúc lan tỏa sức sống khắp nơi",
        "Tôi hạnh phúc hồi phục nhanh chóng và hoàn toàn",
        "Tôi hạnh phúc sống khỏe mạnh toàn diện – thân, tâm, trí",
      ],
    },

    /* ---------- 4. Tình Yêu & Mối Quan Hệ ---------- */
    {
      id: "relationships",
      title: "Tình Yêu & Mối Quan Hệ",
      affirmations: [
        "Tôi hạnh phúc cho và nhận tình yêu vô điều kiện",
        "Tôi hạnh phúc giao tiếp cởi mở",
        "Tôi hạnh phúc lắng nghe với lòng thấu cảm",
        "Tôi hạnh phúc tôn trọng ranh giới lành mạnh",
        "Tôi hạnh phúc bày tỏ yêu thương tự nhiên",
        "Tôi hạnh phúc biết ơn bạn đời mỗi ngày",
        "Tôi hạnh phúc tạo khoảnh khắc đáng nhớ",
        "Tôi hạnh phúc thứ tha và buông bỏ nhanh chóng",
        "Tôi hạnh phúc cùng nhau lớn lên qua thử thách",
        "Tôi hạnh phúc chia sẻ cảm xúc chân thật",
        "Tôi hạnh phúc truyền cảm hứng cho ước mơ của người yêu",
        "Tôi hạnh phúc trân trọng sự khác biệt",
        "Tôi hạnh phúc vun đắp niềm tin sâu sắc",
        "Tôi hạnh phúc hỗ trợ độc lập lẫn nhau",
        "Tôi hạnh phúc giải quyết mâu thuẫn êm đẹp",
        "Tôi hạnh phúc ưu tiên thời gian chất lượng",
        "Tôi hạnh phúc tạo bất ngờ vui vẻ",
        "Tôi hạnh phúc thu hút người nâng tầm mình",
        "Tôi hạnh phúc giữ lửa lãng mạn",
        "Tôi hạnh phúc sống thật trong tình yêu",
        "Tôi hạnh phúc nuôi dưỡng sự thân mật và tiếng cười",
        "Tôi hạnh phúc xây đắp tình yêu nuôi dưỡng tâm hồn",
      ],
    },

    /* ---------- 5. Gia Đình & Bạn Bè ---------- */
    {
      id: "family",
      title: "Gia Đình & Bạn Bè",
      affirmations: [
        "Tôi hạnh phúc cảm thấy kết nối với gia đình",
        "Tôi hạnh phúc tôn vinh cội nguồn của chúng tôi",
        "Tôi hạnh phúc biết ơn cha mẹ sâu sắc",
        "Tôi hạnh phúc gắn bó vui vẻ với anh chị em",
        "Tôi hạnh phúc tạo truyền thống mới ý nghĩa",
        "Tôi hạnh phúc có mặt khi người thân cần",
        "Tôi hạnh phúc ăn mừng cột mốc cùng nhau",
        "Tôi hạnh phúc trao hỗ trợ vô điều kiện",
        "Tôi hạnh phúc chia sẻ tiếng cười và câu chuyện",
        "Tôi hạnh phúc tôn trọng sự độc đáo của mỗi người",
        "Tôi hạnh phúc giữ bạn cũ bền chặt",
        "Tôi hạnh phúc chào đón bạn mới nhiệt tình",
        "Tôi hạnh phúc lên kế hoạch buổi họp mặt ý nghĩa",
        "Tôi hạnh phúc giao tiếp với sự tử tế",
        "Tôi hạnh phúc hóa giải hiểu lầm nhanh chóng",
        "Tôi hạnh phúc thứ tha người thân hoàn toàn",
        "Tôi hạnh phúc đón nhận tình thương từ vòng tròn của mình",
        "Tôi hạnh phúc kiên nhẫn và từ bi",
        "Tôi hạnh phúc khích lệ ước mơ người thân",
        "Tôi hạnh phúc là nguồn năng lượng tích cực",
        "Tôi hạnh phúc cảm thấy an toàn, được yêu thương và hỗ trợ",
        "Tôi hạnh phúc nuôi dưỡng gắn kết bền vững trọn đời",
      ],
    },

    /* ---------- 6. Phát Triển Cá Nhân ---------- */
    {
      id: "growth",
      title: "Phát Triển Cá Nhân",
      affirmations: [
        "Tôi hạnh phúc mở rộng trí tuệ mỗi ngày",
        "Tôi hạnh phúc tìm kiếm tri thức khắp nơi",
        "Tôi hạnh phúc học hỏi từ sai lầm",
        "Tôi hạnh phúc đọc những cuốn sách truyền cảm hứng",
        "Tôi hạnh phúc đầu tư cho giáo dục của mình",
        "Tôi hạnh phúc luyện tập ngôn ngữ mới",
        "Tôi hạnh phúc trau dồi tài năng",
        "Tôi hạnh phúc thách thức niềm tin giới hạn",
        "Tôi hạnh phúc giữ tâm khám phá và cởi mở",
        "Tôi hạnh phúc đón nhận phản hồi xây dựng",
        "Tôi hạnh phúc đặt mục tiêu học tập rõ ràng",
        "Tôi hạnh phúc theo dõi tiến trình phát triển",
        "Tôi hạnh phúc ôm trọn tinh thần học suốt đời",
        "Tôi hạnh phúc thiền định và tự phản tỉnh",
        "Tôi hạnh phúc phát triển trí tuệ cảm xúc",
        "Tôi hạnh phúc duy trì kỷ luật và kiên định",
        "Tôi hạnh phúc ăn mừng từng bước tiến",
        "Tôi hạnh phúc làm người thầy và người học",
        "Tôi hạnh phúc chuyển kiến thức thành hành động",
        "Tôi hạnh phúc đồng bộ phát triển với mục đích sống",
        "Tôi hạnh phúc khai mở tiềm năng vô hạn",
        "Tôi hạnh phúc tiến hóa thành phiên bản tốt nhất của chính mình",
      ],
    },

    /* ---------- 7. Niềm Vui & Giải Trí ---------- */
    {
      id: "fun",
      title: "Niềm Vui & Giải Trí",
      affirmations: [
        "Tôi hạnh phúc dành thời gian cho sự vui chơi",
        "Tôi hạnh phúc khám phá sở thích mới",
        "Tôi hạnh phúc cười thật to và thường xuyên",
        "Tôi hạnh phúc du lịch và khám phá",
        "Tôi hạnh phúc nhảy múa hết mình",
        "Tôi hạnh phúc hát ca với niềm vui",
        "Tôi hạnh phúc tận hưởng vẻ đẹp thiên nhiên",
        "Tôi hạnh phúc sống ngẫu hứng tích cực",
        "Tôi hạnh phúc ăn mừng chiến thắng nhỏ",
        "Tôi hạnh phúc tham gia sự kiện nâng tầm",
        "Tôi hạnh phúc thử sức nghệ thuật sáng tạo",
        "Tôi hạnh phúc thư giãn không cảm giác tội lỗi",
        "Tôi hạnh phúc sắp xếp chuyến phiêu lưu mini",
        "Tôi hạnh phúc mang niềm vui vào công việc thường nhật",
        "Tôi hạnh phúc chơi thể thao vì đam mê",
        "Tôi hạnh phúc thưởng thức món ăn tuyệt vời",
        "Tôi hạnh phúc lưu giữ kỷ niệm hạnh phúc",
        "Tôi hạnh phúc chia sẻ tiếng cười cùng bạn bè",
        "Tôi hạnh phúc cảm thấy trẻ trung ở mọi lứa tuổi",
        "Tôi hạnh phúc cân bằng công việc và vui chơi",
        "Tôi hạnh phúc thêm gia vị phấn khích vào cuộc sống",
        "Tôi hạnh phúc sống mỗi ngày với ánh nhìn hồn nhiên",
      ],
    },

    /* ---------- 8. Môi Trường Sống ---------- */
    {
      id: "environment",
      title: "Môi Trường Sống",
      affirmations: [
        "Tôi hạnh phúc sống trong không gian sạch đẹp",
        "Tôi hạnh phúc sắp xếp môi trường gọn gàng",
        "Tôi hạnh phúc giữ lại những vật mang niềm vui",
        "Tôi hạnh phúc mở cửa đón ánh sáng tự nhiên",
        "Tôi hạnh phúc hít thở không khí trong lành",
        "Tôi hạnh phúc trang trí có chủ đích và thẩm mỹ",
        "Tôi hạnh phúc duy trì bàn làm việc ngăn nắp",
        "Tôi hạnh phúc cảm thấy an toàn và thoải mái tại nhà",
        "Tôi hạnh phúc chào đón khách bằng nụ cười",
        "Tôi hạnh phúc chăm sóc cây xanh tươi tốt",
        "Tôi hạnh phúc tái chế và giảm rác thải",
        "Tôi hạnh phúc ủng hộ thói quen thân thiện môi trường",
        "Tôi hạnh phúc trân trọng không gian công cộng",
        "Tôi hạnh phúc thiết kế không gian kích thích sáng tạo",
        "Tôi hạnh phúc giữ xe cộ sạch sẽ và an toàn",
        "Tôi hạnh phúc tận hưởng tầm nhìn truyền cảm hứng",
        "Tôi hạnh phúc sửa chữa và bảo trì kịp thời",
        "Tôi hạnh phúc thêm hương thơm, âm thanh dễ chịu",
        "Tôi hạnh phúc tạo góc nghỉ ấm cúng",
        "Tôi hạnh phúc giữ khu vực yên tĩnh linh thiêng",
        "Tôi hạnh phúc cảm thấy vững chãi ở bất cứ nơi đâu",
        "Tôi hạnh phúc sống trong môi trường nuôi dưỡng con người tốt đẹp nhất của tôi",
      ],
    },

    /* ---------- 9. Tâm Linh & Bình An Nội Tâm ---------- */
    {
      id: "spirituality",
      title: "Tâm Linh & Bình An Nội Tâm",
      affirmations: [
        "Tôi hạnh phúc cảm thấy kết nối với mục đích cao cả",
        "Tôi hạnh phúc thiền định một cách dễ dàng",
        "Tôi hạnh phúc tin tưởng vào hướng dẫn bên trong",
        "Tôi hạnh phúc thực hành lòng biết ơn mỗi ngày",
        "Tôi hạnh phúc nuôi dưỡng lòng từ bi cho mọi sinh linh",
        "Tôi hạnh phúc tha thứ cho bản thân hoàn toàn",
        "Tôi hạnh phúc buông lo lắng cho vũ trụ",
        "Tôi hạnh phúc ôm trọn tĩnh lặng và yên bình",
        "Tôi hạnh phúc thấy sự thiêng liêng trong điều bình thường",
        "Tôi hạnh phúc hành động phù hợp với giá trị cốt lõi",
        "Tôi hạnh phúc sống trọn khoảnh khắc hiện tại",
        "Tôi hạnh phúc lan tỏa lòng yêu thương",
        "Tôi hạnh phúc ghi chép lại tuệ giác tâm linh",
        "Tôi hạnh phúc tụng niệm với chánh niệm",
        "Tôi hạnh phúc tôn trọng mọi con đường chân lý",
        "Tôi hạnh phúc hít vào bình an cho từng tế bào",
        "Tôi hạnh phúc bỏ phán xét và trách móc",
        "Tôi hạnh phúc cử hành nghi lễ thiêng liêng",
        "Tôi hạnh phúc cảm thấy được dẫn dắt và bảo vệ",
        "Tôi hạnh phúc tỏa ánh sáng nội tâm ra ngoài",
        "Tôi hạnh phúc trải nghiệm sự hợp nhất với cuộc sống",
        "Tôi hạnh phúc lan tỏa sự an nhiên, đức tin và tình yêu",
      ],
    },

    /* ---------- 10. Đóng Góp & Cộng Đồng ---------- */
    {
      id: "contribution",
      title: "Đóng Góp & Cộng Đồng",
      affirmations: [
        "Tôi hạnh phúc chia sẻ tài năng rộng rãi",
        "Tôi hạnh phúc tình nguyện thời gian và kỹ năng",
        "Tôi hạnh phúc nâng tầm cộng đồng của mình",
        "Tôi hạnh phúc hướng dẫn người cần chỉ dẫn",
        "Tôi hạnh phúc quyên góp tài lực đầy niềm vui",
        "Tôi hạnh phúc ủng hộ các hoạt động xã hội",
        "Tôi hạnh phúc cất tiếng nói cho công lý",
        "Tôi hạnh phúc trao quyền cho người khác thành công",
        "Tôi hạnh phúc thực hiện hành động tử tế bất ngờ",
        "Tôi hạnh phúc hợp tác tạo thay đổi tích cực",
        "Tôi hạnh phúc truyền hy vọng bằng hành động",
        "Tôi hạnh phúc ăn mừng chiến thắng tập thể",
        "Tôi hạnh phúc lắng nghe nhu cầu cộng đồng",
        "Tôi hạnh phúc bảo vệ những người yếu thế",
        "Tôi hạnh phúc lãnh đạo với sự chính trực",
        "Tôi hạnh phúc chia sẻ kiến thức đã học",
        "Tôi hạnh phúc tạo cơ hội cho mọi người",
        "Tôi hạnh phúc gieo hạt cho thế hệ tương lai",
        "Tôi hạnh phúc khuếch đại tiếng nói đa dạng",
        "Tôi hạnh phúc xây dựng môi trường hòa nhập",
        "Tôi hạnh phúc phụng sự với trái tim hân hoan",
        "Tôi hạnh phúc để lại thế giới tốt đẹp hơn khi tôi đến",
      ],
    },
  ],
};

// Music tracks
export const MUSIC_TRACKS = [
  {
    id: "ambient",
    title: "Ambient",
    src: "/audio/ambient.mp3",
  },
  {
    id: "meditation",
    title: "Deep Meditation",
    src: "/audio/deep-meditation.mp3",
  },
  {
    id: "nature",
    title: "Nature Sounds",
    src: "/audio/nature-sound.mp3",
  },
];

// For demo purposes, we'll use placeholder audio files
// In a real app, you would use actual audio files
export const PLACEHOLDER_AUDIO =
  "https://assets.mixkit.co/music/preview/mixkit-relaxing-in-nature-522.mp3"; 